FROM postgres:latest

# You can create custom docker image by adding your own configurations here

# Set environment variables for PostgreSQL
# ENV POSTGRES_DB=testdb
# ENV POSTGRES_USER=testuser
# ENV POSTGRES_PASSWORD=testpassword

# Expose PostgreSQL default port
EXPOSE 5432